# Generated by Django 5.1 on 2025-04-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userproductreaction'),
        ('core', '0014_alter_product_brand'),
    ]

    operations = [
    ]
