# Generated by Django 5.2 on 2025-06-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userproductreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
