# Generated by Django 5.2 on 2025-06-29 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='category',
            field=models.ForeignKey(help_text='تصنيف المنتج المرتبط بالمواصفة', on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
