# Generated by Django 5.2 on 2025-06-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_specification_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='category',
        ),
    ]
